a=input("enter first input:")
b=input("enter second input:")
print("the overall sum is:",int(a)+float(b))
print("the overall difference is:",int(a)-float(b))
print("the overall product is:",int(a)*float(b))
print("the overall exponentresult is:",int(a)**float(b))
print("the overall floor division is:",int(a)//float(b))
print("the overall modulus is:",int(a)%float(b))
print("the overall division is:",int(a)/float(b))
# print(int(a)+float(b)